TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 1.5
  acc_lim_x: 1.0
  acc_lim_y: 1.0

  controller_frequency: 10.0

  meter_scoring: true

  holonomic_robot: false
