obstacle_range: 25.0
raytrace_range: 30.0
footprint: [[0.3, 0.3], [0.3, -0.3], [-0.3, -0.3], [-0.3, 0.3]]
#robot_radius: ir_of_robot
inflation_radius: 0.15

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true} 

