local_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  resolution: 0.05
  width: 30.0
  height: 30.0
  origin_x: 5.0
  origin_y: 5.0
