  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  r2d2_head_controller:
    type: "effort_controllers/JointPositionController"
    joint: torso_head_joint
    pid: {p: 150.0, i: 0.04, d: 10.0, i_clamp_max: 100, i_clamp_min: -100}

  r2d2_gripper_pole_controller:
    type: "effort_controllers/JointPositionController"
    joint: torso_gripper_pole_joint
    pid: {p: 50.0, i: 0.04, d: 10.0, i_clamp_max: 100, i_clamp_min: -100}

  r2d2_left_gripper_finger_controller:
    type: "effort_controllers/JointPositionController"
    joint: left_gripper_finger_joint
    pid: {p: 5.0, i: 0.04, d: 1.0, i_clamp_max: 100, i_clamp_min: -100}

  r2d2_right_gripper_finger_controller:
    type: "effort_controllers/JointPositionController"
    joint: right_gripper_finger_joint
    pid: {p: 5.0, i: 0.04, d: 1.0, i_clamp_max: 100, i_clamp_min: -100}

  r2d2_gripper_controller:
    type: "effort_controllers/GripperActionController"
    joint: left_gripper_finger_joint
    goal_tolerance: 0.01
    stalled_velocity_threshold: 0.01
    stall_timeout: 0.2
    gains:
      left_gripper_finger_joint: {p: 200, d: 1, i: 5, i_clamp: 1}
 
