<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

	<xacro:macro name="wheel" params="name prefix suffix reflect">

		<link name="${prefix}_${suffix}_wheel">
			<visual>
				<origin xyz="0 0 0" rpy="${pi/2} 0 0" />
				<geometry>
					<cylinder radius="${wheeldiam/2}" length="0.1"/>
				</geometry>
				<material name="Black"/>
				<origin xyz="0 0 0" rpy="0 0 0" />
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="${pi/2} 0 0" />
				<geometry>
					<cylinder radius="${wheeldiam/2}" length="0.1"/>
				</geometry>
				<origin xyz="0 0 0" rpy="0 0 0" />
			</collision>
			<xacro:default_inertial mass="1"/>
		</link>
		<xacro:gazebo_material link="${prefix}_${suffix}_wheel" color="Black"/>

		<joint name="${prefix}_${suffix}_wheel_joint" type="continuous">
			<axis xyz="0 1 0" rpy="0 0 0" />
			<parent link="${prefix}_leg_base"/>
			<child link="${prefix}_${suffix}_wheel"/>
			<origin xyz="${baselen*reflect/3} 0 -${wheeldiam/2+.05}" rpy="0 0 0"/>
		</joint>

		<!-- This block connects the wheel joint to an actuator (motor), which informs both
		simulation and visualization of the robot -->
		<transmission name="${prefix}_${suffix}_wheel_trans" type="SimpleTransmission">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="${prefix}_${suffix}_wheel_joint">
				<hardwareInterface>VelocityJointInterface</hardwareInterface>
				<mechanicalReduction>1</mechanicalReduction>
			</joint>

			<actuator name="${prefix}_${suffix}_wheel_motor">
				<hardwareInterface>EffortJointInterface</hardwareInterface>
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
		</transmission>

	</xacro:macro>

</robot>
