<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

	<xacro:macro name="gazebo_material" params="link color">
		<gazebo reference="${link}">
			<material>Gazebo/${color}</material>
		</gazebo>
	</xacro:macro>

	<gazebo>
		<!-- Gazebo plugin for ROS Control -->
		<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"> </plugin>
	</gazebo>
		
	<gazebo>
		<!-- Gazebo plugin for skid steering -->
		<plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
			<alwaysOn>true</alwaysOn>
			<updateRate>50.0</updateRate>
			<leftFrontJoint>left_front_wheel_joint</leftFrontJoint>
			<rightFrontJoint>right_front_wheel_joint</rightFrontJoint>
			<leftRearJoint>left_back_wheel_joint</leftRearJoint>
			<rightRearJoint>right_back_wheel_joint</rightRearJoint>
			<wheelSeparation>${2.0*baselen/3.0}</wheelSeparation>
			<wheelDiameter>${wheeldiam}</wheelDiameter>
			<torque>20</torque>
			<broadcastTF>1</broadcastTF>
			<odometryFrame>map</odometryFrame>
			<commandTopic>cmd_vel</commandTopic>
			<odometryTopic>r2d2/odom</odometryTopic>
			<robotBaseFrame>base_link</robotBaseFrame>
		</plugin>
	</gazebo>

	<gazebo reference="hokuyo_link">
		<!-- Gazebo plugin for hokuyo laser -->
		<sensor type="gpu_ray" name="head_hokuyo_sensor">
			<pose>0 0 0 0 0 0</pose>
			<visualize>true</visualize>
			<update_rate>40</update_rate>
			<ray>
				<scan>
					<horizontal>
						<samples>720</samples>
						<resolution>1</resolution>
						<min_angle>-1.570796</min_angle>
						<max_angle>1.570796</max_angle>
					</horizontal>
				</scan>
				<range>
					<min>0.10</min>
					<max>30.0</max>
					<resolution>0.01</resolution>
				</range>
				<noise>
					<type>gaussian</type>
					<!-- Noise parameters based on published spec for Hokuyo laser
							 achieving "+-30mm" accuracy at range < 10m.	A mean of 0.0m and
							 stddev of 0.01m will put 99.7% of samples within 0.03m of the true
							 reading. -->
					<mean>0.0</mean>
					<stddev>0.01</stddev>
				</noise>
			</ray>
			<plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_gpu_laser.so">
				<topicName>/r2d2/laser/scan</topicName>
				<frameName>hokuyo_link</frameName>
			</plugin>
		</sensor>
	</gazebo>

</robot>
